# Generated by Django 4.0.6 on 2022-07-17 05:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_bio_userprofile_is_club_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('about', models.CharField(max_length=256)),
                ('institute', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, upload_to=api.models.Upload_path_handler)),
            ],
            options={
                'unique_together': {('name', 'institute')},
            },
        ),
    ]
