# Generated by Django 4.0.6 on 2022-07-27 17:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Upload_path_handler),
        ),
    ]
