# Generated by Django 4.0.6 on 2022-07-30 22:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_club_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_1', models.CharField(max_length=32)),
                ('op_2', models.CharField(max_length=32)),
                ('op_3', models.CharField(max_length=32)),
                ('op_4', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_type', models.CharField(max_length=32)),
                ('answer', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.Upload_path_handler)),
                ('question_time', models.CharField(max_length=128)),
            ],
        ),
    ]
