# Generated by Django 4.0.2 on 2022-07-29 06:16

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_club_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op1', models.CharField(blank=True, max_length=32, null=True)),
                ('op2', models.CharField(blank=True, max_length=32, null=True)),
                ('op3', models.CharField(blank=True, max_length=32, null=True)),
                ('op4', models.CharField(blank=True, max_length=32, null=True)),
                ('correct_option', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'unique_together': {('op1', 'op2', 'op3', 'op4', 'correct_option')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('question', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.Question_image_path_handler)),
                ('answer', models.CharField(max_length=32)),
                ('point', models.IntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.option')),
            ],
            options={
                'unique_together': {('question', 'option')},
            },
        ),
    ]
