# Generated by Django 4.0.6 on 2022-07-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_options_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
    ]
