# Generated by Django 4.0.6 on 2022-07-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
