# Generated by Django 4.0.2 on 2022-07-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_option_question'),
        ('api', '0008_delete_question'),
    ]

    operations = [
    ]
