# Generated by Django 4.0.2 on 2022-07-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_0006_option_question_0008_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='ques_type',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='General', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='question_time',
            field=models.CharField(default=10, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('ques_type', 'answer', 'question_time', 'point')},
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_1', models.CharField(max_length=32)),
                ('op_2', models.CharField(max_length=32)),
                ('op_3', models.CharField(max_length=32)),
                ('op_4', models.CharField(max_length=32)),
                ('correct_op', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('op_1', 'op_2', 'op_3', 'op_4', 'correct_op')},
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='option',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
