# Generated by Django 4.0.2 on 2022-07-31 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_type_question_ques_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('ques_type', 'answer', 'point')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_time',
        ),
    ]
