# Generated by Django 4.0.2 on 2022-07-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_question_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='GK', max_length=32),
        ),
    ]
