# Generated by Django 4.0.6 on 2022-07-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
