# Generated by Django 4.0.2 on 2022-08-08 19:25

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_alter_question_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('about', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.club')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterUniqueTogether(
            name='options',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('ques_type', 'answer', 'point')},
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Question_image_path_handler),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.options'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quiz', to='api.Question'),
        ),
        migrations.RemoveField(
            model_name='options',
            name='correct_op',
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('name', 'created_by')},
        ),
    ]
