# Generated by Django 4.0.2 on 2022-08-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_quiz_delete_group_alter_options_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('ques_type', 'options', 'category', 'answer', 'point')},
        ),
    ]
