# Generated by Django 4.0.2 on 2022-08-08 19:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_question_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('about', models.CharField(max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.Category_image_path_handler)),
            ],
            options={
                'unique_together': {('name', 'about')},
            },
        ),
    ]
