# Generated by Django 4.0.6 on 2022-08-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('ques_type', 'options', 'category', 'answer')},
        ),
    ]
