# Generated by Django 4.0.2 on 2022-08-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quote',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
