# Generated by Django 4.0.2 on 2022-08-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_category_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_club_member',
            new_name='is_club_admin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='api.club'),
        ),
    ]
