# Generated by Django 4.0.2 on 2022-08-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_club_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='club',
        ),
    ]
