# Generated by Django 4.0.2 on 2022-08-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_userprofile_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='club',
            field=models.ManyToManyField(blank=True, null=True, related_name='club', to='api.Club'),
        ),
    ]
