# Generated by Django 4.0.6 on 2022-08-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_club_members_userprofile_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='club',
        ),
        migrations.CreateModel(
            name='ClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(max_length=32, null=True)),
                ('user_id', models.CharField(max_length=256, null=True)),
            ],
            options={
                'unique_together': {('club_id', 'user_id')},
            },
        ),
    ]
