# Generated by Django 4.0.2 on 2022-08-13 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_remove_userprofile_club_clubuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuser',
            name='designation',
            field=models.CharField(default='Member', max_length=32),
        ),
        migrations.AddField(
            model_name='clubuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='club_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.club'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
