# Generated by Django 4.0.6 on 2022-08-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_clubuser_designation_clubuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('quiz_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.quiz')),
            ],
            options={
                'unique_together': {('quiz_id', 'question_id')},
            },
        ),
    ]
