# Generated by Django 4.0.6 on 2022-08-24 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0030_alter_question_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1', models.IntegerField(default=0)),
                ('player_2', models.IntegerField(default=0)),
                ('cur_pt_1', models.IntegerField(default=0)),
                ('cur_pt_2', models.IntegerField(default=0)),
                ('name_1', models.CharField(default='Player 1', max_length=32)),
                ('name_2', models.CharField(default='Player 2', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'name')},
            },
        ),
    ]
